name: snakeapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_auth: ^4.2.2
  firebase_core: ^2.7.0
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0

  provider: ^6.0.5
  file_picker: ^5.2.5
  permission_handler: ^10.2.0
  intl: ^0.18.0

  fluttertoast: ^8.2.1

  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  scrollable_positioned_list: ^0.3.5

  url_launcher: ^6.1.10
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg